services:
  a:
    image: stream-container:latest
    command: ["node", "index.js", "-p", "http://vocab.ex.org/a", "-w", "#window0_3 0 3"]
    ports:
      - 9000:8080
  aa:
    image: stream-container:latest
    command: ["node", "index.js", "-p", "http://vocab.ex.org/aa", "-w", "#window0_3 0 3"]
    ports:
      - 9001:8080
  b:
    image: stream-container:latest
    command: ["node", "index.js", "-p", "http://vocab.ex.org/b", "-w", "#window0_0 0 0"]
    ports:
      - 9002:8080
  bb:
    image: stream-container:latest
    command: ["node", "index.js", "-p", "http://vocab.ex.org/bb", "-w", "#window0_0 0 0"]
    ports:
      - 9003:8080
  rn0:
    image: reasoning-agent:latest
    command: ["node", "index.js", "DIAMOND", "-g", "http://b:8080 b ?x", "-s", "http://a:8080/#window0_3 ?x "]
  rn1:
    image: reasoning-agent:latest
    command: ["node", "index.js", "BOX", "-g", "http://bb:8080 bb ?x", "-s", "http://aa:8080/#window0_3 ?x"]